#Lesson 3 Notes: Loops


---
Lesson Learnings

---

Python reccomend snake case over camel case when naming variables(ex. variable for someones first name is firstName (in camel case) and first_name (in snake case)

- While : used to loop while the conditional statement in question is true
- For : used primarily to loop through lists and any other iterable type of data (including arrays, dictionaries, etc.)
- list : is a datatype in python used to store lists of values (lists in python are 0 indexed by default)
- listName[number] : is used to get a partictular index within a list in python
- range : is a function used to create a list of numbers from zero (or specified start) to a specified amount
- dict: is a data structure that has a set of keys with associated values (like a dictionary in real life has words attached to associated definitions)

In [10]:
#a while loop
x = 4
while x > 0:
  print("Ayo")
  x -= 1



#a for loop (reccomendation is to use an _ over another type of variable if its only being used for the for loop otherwise use a different variable)
for _ in range(3):
  print("test")

#I used the variable i here because I was refencing it throughout the code 
for i in range(3):
  print(i)


#repeat lines multiple times
print("fire \n" * 3, end="")

# infinite loop to make sure user properly inputs values
while True:
  number = int(input("whats n? "))

  if number > 0:
    break

for _ in range(number):
  print("print me")

Ayo
Ayo
Ayo
Ayo
test
test
test
0
1
2
fire
fire
fire
whats n? 13
print me
print me
print me
print me
print me
print me
print me
print me
print me
print me
print me
print me
print me
['tesla', 'luicd', 'ford', 'rimac']

In [ ]:
#create a list and print 

cars = ["tesla", "luicd", "ford", "rimac"]
#prints entire list 
print(cars)
#prints the 2 value in the list
print(cars[1])

#use for loop to iterate through list
for student in cars:
  print(student)

#another way
for t in range(len(cars)):
  print(cars[i])

In [13]:

#dictionary of trucks and their associated horsepower the key values are the strings and the values are the numbers

trucks = {
    "Ram TRX": 707,
    "Ford Raptor": 560,
    "Silverado ZZ1": 410
}

# in a dictionary the keys can be thought of and treated as the indexs for the values
print ("horsepower for the Ram TRX ", trucks["Ram TRX"])


#print the keys (aka truck name) and then the values (aka horsepower)
for truck in trucks:
  print(truck, trucks[truck])

horsepower for the Ram TRX  707
Ram TRX 707
Ford Raptor 560
Silverado ZZ1 410

In [16]:
#lists of dictionaries
suvs = [
    {"make": "BMW", "model": "x5 M", "cost": 115000, "Horsepower": 607},
    {"make": "Mercedes", "model": "GLE 63 s", "cost": 125000, "Horsepower": 580},
    {"make": "Tesla", "model": "Model X Plaid", "cost": 155000, "Horsepower": 1090}
]

#prints the model of vehicle
for suv in suvs:
  print(suv["make"], suv["model"], suv["cost"], suv["Horsepower"], sep=", ")

BMW, x5 M, 115000, 607
Mercedes, GLE 63 s, 125000, 580
Tesla, Model X Plaid, 155000, 1090